### ISSUE TITLE
Wrong API

### ISSUE THREAD

**Issue by CarnageMarkus** [Kirides/union-manareg#1]
https://github.com/Kirides/union-manareg/blob/02bc9df7b1456b6e4a60b44e0bb041228392af58/Union_ManaReg/Application.cpp#L13

Hi, not sure if address is bad, but you are mixing #ifdef __G1 with G1Addon namespace...

**Comment by kirides** [comment]
Woopsie daisy - gonna have a fix out by tomorrow.

Must somehow slipped through while i refactored the code.
This leads to a non-working mana-regeneration for G1 😨 

This explains [this issue](https://forum.worldofplayers.de/forum/threads/1541416-UNION-Mana-Regeneration?p=26179591&viewfull=1#post26179591)

**Comment by kirides** [comment]
fixed with latest commit
